### ISSUE TITLE
Migration to v12

### ISSUE THREAD

**Issue by atchuthan** [sodexis/avatax_connector#10]
We had a customer who needed the module avatax_connector to be migrated to v12 as the customer was previously using the v10.
So, we have created a forked branch for v12 and others are welcome to QA it.
https://github.com/atchuthan/avatax_connector/tree/12.0-migration

@fhe-odoo Let me know if you are planning to create v12 branch in the repository such that I could create PR for v12.  Thanks.

**Comment by dreispt** [comment]
Fixed by #13
