### ISSUE TITLE
Can not validate an invoice which was validated and canceled before

### ISSUE THREAD

**Issue by dreispt** [sodexis/avatax_connector#15]
# Error

AvaTax: Error: DocStatusError
Summary: DocStatus is invalid for this operation.
Details: Expected Saved\|Posted
Severity: Error

# Scenario

1. Validate an invoice
2. Cancel that invoice
3. Set that invoice to draft
4. Edit invoice lines (or no need to do it), then validate that invoice again

**Comment by dreispt** [comment]
@duyhvu AFAIK this workflow is not supported by Odoo: once an Invoice is validated, it can't be Cancelled and then re-Validated.
Instead you need to create a Credit Note to revert the original invoice to correct, and (if still needed) then create a new Invoice with the correct data. The is a new invoice with a different number.

**Comment by duyhvu** [comment]
It is OOTB in Odoo if you  install module named "account_cancel", and make journal to can be cancelled.



[Video_2019-11-01_233804.zip](https://github.com/sodexis/avatax_connector/files/3798783/Video_2019-11-01_233804.zip)


I attached a video to explain but here is the scenario:

1. Install module "account_cancel"
2. Make Journal can be canceled (there is an option on Journal form)
3. Create an invoice and validate it
4. There is a button named "Cancel" on form to let user cancel that invoice
5. User makes the invoice to draft state and edit it before validating again

**Comment by duyhvu** [comment]
@dreispt Hi do you have any update about this issue >

**Comment by dreispt** [comment]
@duyhvu Avatax does not allow to communicate the same Invoice number a second time.
So I'm not sure how we can process here.

**Comment by duyhvu** [comment]
I will discuss with my team and get back to you
