### ISSUE TITLE
Need to be confirmed that Avalara will calculate tax for customer outside US and CA

### ISSUE THREAD

**Issue by dreispt** [sodexis/avatax_connector#17]

**Comment by dreispt** [comment]
@duyhvu I need some clarification on this:
At this point the Avalara Connector does not support tax calculation outside US and CA. If this is needed, we would need to add this as a feature.
Odoo should still be able to perform regular tax computations in these cases. if not, that's a bug.

**Comment by duyhvu** [comment]
Oh I think this one is just to ask for confirmation that Avalara Connector only support US and CA. If it is, then you can close this ticket

**Comment by dreispt** [comment]
Closing, as it was clarified that at this moment the Avatax connector is not prepared to handle invoices outside US and CA,
