### ISSUE TITLE
Fails Odoo Tests v11

### ISSUE THREAD

**Issue by andrewdhastings** [sodexis/avatax_connector#22]
Fails Odoo.sh automated tests

Date	Level	Type	Message
12/26/2019 15:21:31	ERROR	server	Module sale: 0 failures, 2 errors
12/26/2019 15:21:31	ERROR	server	FAILED
12/26/2019 15:21:31	ERROR	server	` odoo.exceptions.UserError: ('Your Avatax Countries settings are not configured. You need a country code in the Countries section.  \nIf you have a multi-company installation, you must add settings for each company.  \n\nYou can update settings in Avatax->Avatax API.', '')
12/26/2019 15:21:31	ERROR	server	`     raise UserError(_('Your Avatax Countries settings are not configured. You need a country code in the Countries section.  \nIf you have a multi-company installation, you must add settings for each company.  \n\nYou can update settings in Avatax->Avatax API.'))
12/26/2019 15:21:31	ERROR	server	`   File "/home/odoo/src/user/avatax_connector/models/sale_order.py", line 169, in compute_tax
12/26/2019 15:21:31	ERROR	server	`     res.compute_tax()
12/26/2019 15:21:31	ERROR	server	`   File "/home/odoo/src/user/avatax_connector/models/sale_order.py", line 42, in create
12/26/2019 15:21:31	ERROR	server	`     'pricelist_id': self.env.ref('product.list0').id,
12/26/2019 15:21:31	ERROR	server	`   File "/home/odoo/src/odoo/addons/sale/tests/test_sale_to_invoice_and_to_be_invoiced.py", line 41, in test_sale_to_invoice_and_to_be_invoiced
12/26/2019 15:21:31	ERROR	server	Traceback (most recent call last):
12/26/2019 15:21:31	ERROR	server	` Testing amount to invoice and amount to be invoiced, with advances.
12/26/2019 15:21:31	ERROR	server	ERROR: test_sale_to_invoice_and_to_be_invoiced (odoo.addons.sale.tests.test_sale_to_invoice_and_to_be_invoiced.TestSaleOrderInvoicing)
12/26/2019 15:21:31	ERROR	server	` odoo.exceptions.UserError: ('Your Avatax Countries settings are not configured. You need a country code in the Countries section.  \nIf you have a multi-company installation, you must add settings for each company.  \n\nYou can update settings in Avatax->Avatax API.', '')
12/26/2019 15:21:31	ERROR	server	`     raise UserError(_('Your Avatax Countries settings are not configured. You need a country code in the Countries section.  \nIf you have a multi-company installation, you must add settings for each company.  \n\nYou can update settings in Avatax->Avatax API.'))
12/26/2019 15:21:31	ERROR	server	`   File "/home/odoo/src/user/avatax_connector/models/sale_order.py", line 169, in compute_tax
12/26/2019 15:21:31	ERROR	server	`     res.compute_tax()
12/26/2019 15:21:31	ERROR	server	`   File "/home/odoo/src/user/avatax_connector/models/sale_order.py", line 42, in create
12/26/2019 15:21:31	ERROR	server	`     'pricelist_id': self.env.ref('product.list0').id,
12/26/2019 15:21:31	ERROR	server	`   File "/home/odoo/src/odoo/addons/sale/tests/test_sale_to_invoice_and_to_be_invoiced.py", line 153, in test_amount_delivered_and_ordered_qty
12/26/2019 15:21:31	ERROR	server	Traceback (most recent call last):
12/26/2019 15:21:31	ERROR	server	` Testing amount to invoice and amount to be invoiced, with different invoice policy and cancelling SO
12/26/2019 15:21:31	ERROR	server	ERROR: test_amount_delivered_and_ordered_qty (odoo.addons.sale.tests.test_sale_to_invoice_and_to_be_invoiced.TestSaleOrderInvoicing)
12/26/2019 15:21:31	ERROR	server	ERROR
12/26/2019 15:21:30	ERROR	server	ERROR
12/26/2019 15:21:30	ERROR	server	Module sale: 0 failures, 4 errors
12/26/2019 15:21:30	ERROR	server	FAILED
12/26/2019 15:21:30	ERROR	server	` odoo.exceptions.UserError: ('Your Avatax Countries settings are not configured. You need a country code in the Countries section.  \nIf you have a multi-company installation, you must add settings for each company.  \n\nYou can update settings in Avatax->Avatax API.', '')
12/26/2019 15:21:30	ERROR	server	`     raise UserError(_('Your Avatax Countries settings are not configured. You need a country code in the Countries section.  \nIf you have a multi-company installation, you must add settings for each company.  \n\nYou can update settings in Avatax->Avatax API.'))
12/26/2019 15:21:30	ERROR	server	`   File "/home/odoo/src/user/avatax_connector/models/sale_order.py", line 169, in compute_tax
12/26/2019 15:21:30	ERROR	server	`     res.compute_tax()
12/26/2019 15:21:30	ERROR	server	`   File "/home/odoo/src/user/avatax_connector/models/sale_order.py", line 42, in create
12/26/2019 15:21:30	ERROR	server	`     'pricelist_id': self.env.ref('product.list0').id,
12/26/2019 15:21:30	ERROR	server	`   File "/home/odoo/src/odoo/addons/sale/tests/test_sale_order.py", line 79, in test_unlink_cancel
12/26/2019 15:21:30	ERROR	server	Traceback (most recent call last):
12/26/2019 15:21:30	ERROR	server	` Test deleting and cancelling sales orders depending on their state and on the user's rights
12/26/2019 15:21:30	ERROR	server	ERROR: test_unlink_cancel (odoo.addons.sale.tests.test_sale_order.TestSaleOrder)
12/26/2019 15:21:30	ERROR	server	` odoo.exceptions.UserError: ('Your Avatax Countries settings are not configured. You need a country code in the Countries section.  \nIf you have a multi-company installation, you must add settings for each company.  \n\nYou can update settings in Avatax->Avatax API.', '')
12/26/2019 15:21:30	ERROR	server	`     raise UserError(_('Your Avatax Countries settings are not configured. You need a country code in the Countries section.  \nIf you have a multi-company installation, you must add settings for each company.  \n\nYou can update settings in Avatax->Avatax API.'))
12/26/2019 15:21:30	ERROR	server	`   File "/home/odoo/src/user/avatax_connector/models/sale_order.py", line 169, in compute_tax
12/26/2019 15:21:30	ERROR	server	`     res.compute_tax()
12/26/2019 15:21:30	ERROR	server	`   File "/home/odoo/src/user/avatax_connector/models/sale_order.py", line 42, in create
12/26/2019 15:21:30	ERROR	server	`     'company_id': company_1.id,
12/26/2019 15:21:30	ERROR	server	`   File "/home/odoo/src/odoo/addons/sale/tests/test_sale_order.py", line 178, in test_so_create_multicompany
12/26/2019 15:21:30	ERROR	server	Traceback (most recent call last):
12/26/2019 15:21:30	ERROR	server	` In case we use new() outside of an onchange, it might cause the value of related fields to be incorrect. If so, then the company being a related might not be set, which would mean that taxes from all child companies would end up on the order lines.
12/26/2019 15:21:30	ERROR	server	ERROR: test_so_create_multicompany (odoo.addons.sale.tests.test_sale_order.TestSaleOrder)
12/26/2019 15:21:30	ERROR	server	` odoo.exceptions.UserError: ('Your Avatax Countries settings are not configured. You need a country code in the Countries section.  \nIf you have a multi-company installation, you must add settings for each company.  \n\nYou can update settings in Avatax->Avatax API.', '')
12/26/2019 15:21:30	ERROR	server	`     raise UserError(_('Your Avatax Countries settings are not configured. You need a country code in the Countries section.  \nIf you have a multi-company installation, you must add settings for each company.  \n\nYou can update settings in Avatax->Avatax API.'))
12/26/2019 15:21:30	ERROR	server	`   File "/home/odoo/src/user/avatax_connector/models/sale_order.py", line 169, in compute_tax
12/26/2019 15:21:30	ERROR	server	`     res.compute_tax()
12/26/2019 15:21:30	ERROR	server	`   File "/home/odoo/src/user/avatax_connector/models/sale_order.py", line 42, in create
12/26/2019 15:21:30	ERROR	server	`     'pricelist_id': self.env.ref('product.list0').id,
12/26/2019 15:21:30	ERROR	server	`   File "/home/odoo/src/odoo/addons/sale/tests/test_sale_order.py", line 21, in test_sale_order
12/26/2019 15:21:30	ERROR	server	Traceback (most recent call last):
12/26/2019 15:21:30	ERROR	server	` Test the sales order flow (invoicing and quantity updates) - Invoice repeatedly while varrying delivered quantities and check that invoice are always what we expect
12/26/2019 15:21:30	ERROR	server	ERROR: test_sale_order (odoo.addons.sale.tests.test_sale_order.TestSaleOrder)
12/26/2019 15:21:30	ERROR	server	` odoo.exceptions.UserError: ('Your Avatax Countries settings are not configured. You need a country code in the Countries section.  \nIf you have a multi-company installation, you must add settings for each company.  \n\nYou can update settings in Avatax->Avatax API.', '')
12/26/2019 15:21:30	ERROR	server	`     raise UserError(_('Your Avatax Countries settings are not configured. You need a country code in the Countries section.  \nIf you have a multi-company installation, you must add settings for each company.  \n\nYou can update settings in Avatax->Avatax API.'))
12/26/2019 15:21:30	ERROR	server	`   File "/home/odoo/src/user/avatax_connector/models/sale_order.py", line 169, in compute_tax
12/26/2019 15:21:30	ERROR	server	`     res.compute_tax()
12/26/2019 15:21:30	ERROR	server	`   File "/home/odoo/src/user/avatax_connector/models/sale_order.py", line 42, in create
12/26/2019 15:21:30	ERROR	server	`     'pricelist_id': self.env.ref('product.list0').id,
12/26/2019 15:21:30	ERROR	server	`   File "/home/odoo/src/odoo/addons/sale/tests/test_sale_order.py", line 121, in test_cost_invoicing
12/26/2019 15:21:30	ERROR	server	Traceback (most recent call last):
12/26/2019 15:21:30	ERROR	server	` Test confirming a vendor invoice to reinvoice cost on the so
12/26/2019 15:21:30	ERROR	server	ERROR: test_cost_invoicing (odoo.addons.sale.tests.test_sale_order.TestSaleOrder)
12/26/2019 15:21:30	ERROR	server	ERROR
12/26/2019 15:21:29	ERROR	server	ERROR
12/26/2019 15:21:27	ERROR	server	ERROR
12/26/2019 15:21:26	ERROR	server	ERROR
12/26/2019 15:20:01	ERROR	server	Module account: 1 failures, 0 errors
12/26/2019 15:20:01	ERROR	server	FAILED
12/26/2019 15:20:01	ERROR	server	` AssertionError: 100 != 121.0 : The included tax must be subtracted to the price
12/26/2019 15:20:01	ERROR	server	`     self.assertEquals(100, out_line.price_unit, "The included tax must be subtracted to the price")
12/26/2019 15:20:01	ERROR	server	`   File "/home/odoo/src/odoo/addons/account/tests/test_product_id_change.py", line 89, in test_product_id_change
12/26/2019 15:20:01	ERROR	server	Traceback (most recent call last):
12/26/2019 15:20:01	ERROR	server	FAIL: test_product_id_change (odoo.addons.account.tests.test_product_id_change.TestProductIdChange)
12/26/2019 15:20:01	ERROR	server	FAIL
12/26/2019 15:19:33	ERROR	server	Module account: 1 failures, 0 errors
12/26/2019 15:19:33	ERROR	server	FAILED
12/26/2019 15:19:33	ERROR	server	` AssertionError: 1.0 != 1.3
12/26/2019 15:19:33	ERROR	server	`     self.assertEquals(tax_lines[i].amount_total, exp_tax_values[i])
12/26/2019 15:19:33	ERROR	server	`   File "/home/odoo/src/odoo/addons/account/tests/test_account_invoice_rounding.py", line 79, in _check_invoice_rounding
12/26/2019 15:19:33	ERROR	server	`     [100.2], [1.3]
12/26/2019 15:19:33	ERROR	server	`   File "/home/odoo/src/odoo/addons/account/tests/test_account_invoice_rounding.py", line 98, in test_rounding_biggest_tax
12/26/2019 15:19:33	ERROR	server	Traceback (most recent call last):
12/26/2019 15:19:33	ERROR	server	FAIL: test_rounding_biggest_tax (odoo.addons.account.tests.test_account_invoice_rounding.TestAccountInvoiceRounding)
12/26/2019 15:19:33	ERROR	server	FAIL

**Comment by dreispt** [comment]
@atchuthan Want to have a look at this?

**Comment by dreispt** [comment]
Maybe same as #5?
