### ISSUE TITLE
Breaks Website Checkout Process - Can't Save a Quote without Address Validation 

### ISSUE THREAD

**Issue by andrewdhastings** [sodexis/avatax_connector#24]
You cannot save a quote unless the address is fully validated and when you try to checkout on the website you get a 500 error. 

See video for demo - http://somup.com/cqltnif53u

**Comment by dreispt** [comment]
We would need to see the underlying error message. It is shown in the server log.
Have you tried enabling the "Force Address Validation" option?

**Comment by dreispt** [comment]
Is this for v11?

**Comment by andrewdhastings** [comment]
yes this is v11. 

`2020-01-03 18:46:23,935 7 ERROR innopen-gunwerks11-test-avatax-staging-771132 odoo.addons.website.models.ir_http: 500 Internal Server Error:

Traceback (most recent call last):
File "/home/odoo/src/odoo/odoo/addons/base/ir/ir_http.py", line 208, in _dispatch
result = request.dispatch()
File "/home/odoo/src/odoo/odoo/http.py", line 832, in dispatch
r = self._call_function(**self.params)
File "/home/odoo/src/odoo/odoo/http.py", line 344, in _call_function
return checked_call(self.db, *args, **kwargs)
File "/home/odoo/src/odoo/odoo/service/model.py", line 97, in wrapper
return f(dbname, *args, **kwargs)
File "/home/odoo/src/odoo/odoo/http.py", line 337, in checked_call
result = self.endpoint(*a, **kw)
File "/home/odoo/src/odoo/odoo/http.py", line 939, in __call__
return self.method(*args, **kw)
File "/home/odoo/src/odoo/odoo/http.py", line 517, in response_wrap
response = f(*args, **kw)
File "/home/odoo/src/odoo/addons/website_sale/controllers/main.py", line 650, in address
order.partner_id = partner_id
File "/home/odoo/src/odoo/odoo/fields.py", line 991, in __set__
record.write({self.name: write_value})
File "/home/odoo/src/user/avatax_connector/models/sale_order.py", line 62, in write
order.with_context(avatax_recalculation=True).compute_tax()
File "/home/odoo/src/user/avatax_connector/models/sale_order.py", line 213, in compute_tax
currency_id=self.currency_id).TotalTax
File "/home/odoo/src/user/avatax_connector/models/account_tax.py", line 78, in _get_compute_tax
location_code, currency_code, partner.vat_id or None, is_override)
File "/home/odoo/src/user/avatax_connector/models/avalara_api.py", line 198, in get_tax
result = self.get_result(self.taxSvc, self.taxSvc.service.GetTax, request)
File "/home/odoo/src/user/avatax_connector/models/avalara_api.py", line 103, in get_result
raise UserError(_('AvaTax: Warning AvaTax could not validate the street address. \n You can save the address and AvaTax will make an attempt to compute taxes based on the zip code if "Force Address Validation" is disabled in the Avatax connector configuration. \n\n Also please ensure that the company address is set and Validated. You can get there by going to Sales->Customers and removing "Customers" filter from the search at the top. Then go to your company contact info and validate your address in the Avatax Tab'))
odoo.exceptions.UserError: ('AvaTax: Warning AvaTax could not validate the street address. \n You can save the address and AvaTax will make an attempt to compute taxes based on the zip code if "Force Address Validation" is disabled in the Avatax connector configuration. \n\n Also please ensure that the company address is set and Validated. You can get there by going to Sales->Customers and removing "Customers" filter from the search at the top. Then go to your company contact info and validate your address in the Avatax Tab', '')`

**Comment by andrewdhastings** [comment]
No, And here are the current settings. 
![settigns](https://user-images.githubusercontent.com/32532163/71742446-0c183b80-2e1f-11ea-8f7a-7e290e92910c.JPG)

**Comment by andrewdhastings** [comment]
If you turn on "Force Address Validation" you get the same error. 

The problem is the address fails validation. Rather then asking the website customer to fix it or suggest a correct billing it throws an error.

**Comment by dreispt** [comment]
There's a "Disable Address Validation" option, can you try it?
@atchuthan Any suggestions?

**Comment by andrewdhastings** [comment]
Yes already tried that, doesn't make a difference. I dont think that setting even works. Even with it checked it still requires address validation even in the backend. 

Also, as a side note. V12 is a much better design and doesn't bypass odoos fiscal position system. It might be better to simply backport v12 rather then fix all the errors in this one. Just a thought.



⁣Sent from BlueMail ​

**Comment by dreispt** [comment]
We have different maintainers:
Sodexis and @atchuthan created this module, and maintain it up to v11.
Open Source Integrators, through me, took on the v12 migration and maintain it. We also started working on v13.

So I would leave the backport decision to @atchuthan
